= Hello Prod
:docinfo1:
:hardbreaks:
:sectanchors:
:sectnums:
:icons: font
:toc: left
:toc-title: Sommaire
:description: Hello Prod

== Azure cli

* https://docs.microsoft.com/fr-fr/cli/azure/install-azure-cli-windows?tabs=azure-cli
* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/azure_cli

Perform installation _(requires Administrator rights)_

[source,cmd]
.kubectl
----
az aks install-cli
----

== Deployment initialisation

=== Create a Service Principal for GitHub deployment

* https://docs.microsoft.com/fr-fr/cli/azure/create-an-azure-service-principal-azure-cli

[source,cmd]
----
# Select the appropriate subscription
az ad sp create-for-rbac --name "GitHub" --role contributor --sdk-auth
----

WARNING: By default, az ad sp create-for-rbac assigns the Contributor role to the service principal at the subscription scope.

WARNING: Account is valid for one year, so add an update to your calendar ;)

NOTE: Move to publish profile once we stop the deploy/destroy frequently

== Terraform

=== Installation

* https://www.terraform.io/downloads.html
* Unzip & Add to path
	** Edit environemnt variables for your account
	** Add to "Path"
* Check by typing terraform in a Powershell console

=== Usage

[source,cmd]
.Azure
----
# Login into Azure
az login

# Set your default subscription
az account list --output table
az account set --subscription "subscription-id"
az account show --output table
----

[source,cmd]
.Terraform
----
# Initialize Terraform
terraform init

# Optional steps to use workspaces
terraform workspace new poc
terraform workspace select poc

# Check / Deploy
terraform plan
terraform apply

# Destroy all
terraform plan -destroy
terraform destroy

# Format code
terraform fmt -recursive
----

NOTE: You can specify a specific config file using `terraform plan -var-file="./configuration/wps.poc.tfvars"`

== Build & Deploy

[source,cmd]
----
Start Docker Daemon

# Identification lasts only 1 hour
az acr login -n beenotice
mvnw compile jib:build
----

== Annexes

=== Resources

* https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/examples

=== Azure data

[source,cmd]
----
# List locations
az account list-locations -o table

# List App Services runtimes
az webapp list-runtimes --linux
----

https://hub.docker.com/_/microsoft-java-jre


== TODO

* Add tags on created elements (Terrafom: true)

== Demo

[source,cmd]
----
# Tools / Environment
Start Docker Daemon

# Deploy Azure infrastructure
terraform plan
terraform apply

# Build and deploy App
az acr login -n beenotice
mvnw compile jib:build

# Local run
az acr repository show-tags --name beenotice --repository hello-prod --output table
docker pull beenotice.azurecr.io/hello-prod:latest
docker images
docker run --name hello-prod -e "SPRING_PROFILES_ACTIVE=local,prod" -p 8080:8080 -d beenotice.azurecr.io/hello-prod:latest
docker ps -a
docker stop hello-prod
docker rm hello-prod

# Deploy to AKS
az aks get-credentials --resource-group=rg-hello-dev --name=aks-hello-dev



kubectl run hello-prod --image=beenotice.azurecr.io/hello-prod:latest
kubectl expose pod hello-prod --type=LoadBalancer --port=80 --target-port=8080

# Access application
kubectl get all
kubectl get services -o=jsonpath='{.items[*].status.loadBalancer.ingress[0].ip}'
kubectl logs hello-prod

# Performance
gatling run
----